[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nix_verify_souffle"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = ["nix_verify_souffle"]

[tool.hatch.build.targets.wheel.sources]
"nix_verify_souffle" = ["nix_verify_souffle.so"]